name: atamic
dependencies:
  - nbformat
  - pyyaml
  - pytest
  - numpy
  - pandas
  - matplotlib
  - statsmodels
  - patsy
  - jupyter
  - pip:
    - argparse
    - nbval
    - slackclient==1.3.2
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
